### ISSUE TITLE
SecurityException when DO-NOT-DISTURB is active

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#140]
When the device is in DO_NOT_DISTURB mode PAssist is not allowed to change the volume:
```
Exception stack trace:
java.lang.RuntimeException: Unable to stop service com.github.frimtec.android.pikettassist.service.LowSignalService@5e2b8f4: java.lang.SecurityException: Not allowed to change Do Not Disturb state
at android.app.ActivityThread.handleStopService(ActivityThread.java:4148)
at android.app.ActivityThread.access$1900(ActivityThread.java:225)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1902)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:359)
at android.app.ActivityThread.main(ActivityThread.java:7418)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.SecurityException: Not allowed to change Do Not Disturb state
at android.os.Parcel.createException(Parcel.java:2090)
at android.os.Parcel.readException(Parcel.java:2056)
at android.os.Parcel.readException(Parcel.java:2004)
at android.media.IAudioService$Stub$Proxy.setStreamVolume(IAudioService.java:2170)
at android.media.AudioManager.setStreamVolume(AudioManager.java:1175)
at com.github.frimtec.android.pikettassist.service.system.VolumeService.setVolume(VolumeService.java:30)
at com.github.frimtec.android.pikettassist.service.LowSignalService.onDestroy(LowSignalService.java:101)
at android.app.ActivityThread.handleStopService(ActivityThread.java:4128)
... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.audio.AudioService.setStreamVolume(AudioService.java:2385)
at com.android.server.audio.AudioService.setStreamVolume(AudioService.java:2218)
at android.media.IAudioService$Stub.onTransact(IAudioService.java:934)
at android.os.Binder.execTransactInternal(Binder.java:1021)
at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by frimtec** [comment]
Solution: Only change volume when device is in DO_NOT_DISTURB mode.
If DO_NOT_DISTURB is active while on-call state, a error notification should be displayed.
