### ISSUE TITLE
OutOfMemoryError in BitmapFactory

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#146]
If memory is too fragmented on some devices an OutOfMemoryError is possible:
```
Android version: 24 
Device: samsung SM-A510F 
App version: 4100 
Thread name: main 
Exception stack trace: java.lang.OutOfMemoryError: Failed to allocate a 12960012 byte allocation with 10625480 free bytes and 10MB until OOM at
dalvik.system.VMRuntime.newNonMovableArray(Native Method) at
android.graphics.BitmapFactory.nativeDecodeAsset(Native Method) at
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700) at
android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535) at
android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:558) at
android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:588) at
com.github.frimtec.android.pikettassist.ui.overview.StateArrayAdapter.(StateArrayAdapter.java:38) at
com.github.frimtec.android.pikettassist.ui.overview.StateFragment.createAdapter(StateFragment.java:197) at
com.github.frimtec.android.pikettassist.ui.common.AbstractListFragment.refresh(AbstractListFragment.java:67) at
com.github.frimtec.android.pikettassist.ui.common.AbstractListFragment.onResume(AbstractListFragment.java:59) at
com.github.frimtec.android.pikettassist.ui.overview.StateFragment.onResume(StateFragment.java:126) at
androidx.fragment.app.Fragment.performResume(Fragment.java:2649) at
androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922) at
androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238) at
androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) at
androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659) at
androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625) at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268) at
androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479) at
androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468) at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195) at android.app.Activity.performResume(Activity.java:7125) at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821) at
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885) at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692) at
android.os.Handler.dispatchMessage(Handler.java:102) at
android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6776) at
java.lang.reflect.Method.invoke(Native Method) at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by frimtec** [comment]
Memory footprint for decoding traffic light images reduced.
Will be available with Release 1.4.4 shortly.
