### ISSUE TITLE
NullPointerException while checking purchases

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#220]
There seems to be a race condition that can lead to a NPE in rare cases (only reported once so far):

Crash report:
```
Android version: 30
Device: samsung SM-G973F
App version: 49167
Thread name: main

Exception stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.billingclient.api.Purchase$PurchasesResult com.android.billingclient.api.BillingClient.queryPurchases(java.lang.String)' on a null object reference
at com.github.frimtec.android.pikettassist.donation.billing.BillingManager.lambda$queryPurchases$4$BillingManager(BillingManager.java:170)
at com.github.frimtec.android.pikettassist.donation.billing.-$$Lambda$BillingManager$gXo6C1XdX4Dte7WfYK4DPgjJwj8.run(Unknown Source:2)
at com.github.frimtec.android.pikettassist.donation.billing.BillingManager.executeServiceRequest(BillingManager.java:201)
at com.github.frimtec.android.pikettassist.donation.billing.BillingManager.queryPurchases(BillingManager.java:176)
at com.github.frimtec.android.pikettassist.donation.billing.BillingManager.lambda$new$0$BillingManager(BillingManager.java:71)
at com.github.frimtec.android.pikettassist.donation.billing.-$$Lambda$BillingManager$T84MW8CkHUaI3vr5rDSZsuJc4Og.run(Unknown Source:2)
at com.github.frimtec.android.pikettassist.donation.billing.BillingManager$1.onBillingSetupFinished(BillingManager.java:186)
at com.android.billingclient.api.zzae.run(com.android.billingclient:billing@@3.0.2:1)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8425)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by frimtec** [comment]
Cannot reproduce.
