### ISSUE TITLE
Crash report: No Activity found to handle contact

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#243]
Crash report:
```
Android version: 28
Device: samsung SM-A530W
App version: 228853
Thread name: main

Exception stack trace:
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=vnd.android.cursor.dir/contact }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
at android.app.Activity.startActivityForResult(Activity.java:4689)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1278)
at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1266)
at com.github.frimtec.android.pikettassist.ui.overview.StateFragment.lambda$mcsEvuguOVF8mIg-cb0U-c9ULl8(Unknown Source:0)
at com.github.frimtec.android.pikettassist.ui.overview.-$$Lambda$StateFragment$mcsEvuguOVF8mIg-cb0U-c9ULl8.accept(Unknown Source:10)
at com.github.frimtec.android.pikettassist.ui.overview.StateContext.startActivityForResultAction(StateContext.java:107)
at com.github.frimtec.android.pikettassist.ui.overview.OperationsCenterState.actionSelectContact(OperationsCenterState.java:89)
at com.github.frimtec.android.pikettassist.ui.overview.OperationsCenterState.onClickAction(OperationsCenterState.java:52)
at com.github.frimtec.android.pikettassist.ui.overview.StateFragment.lambda$configureListView$0$StateFragment(StateFragment.java:146)
at com.github.frimtec.android.pikettassist.ui.overview.-$$Lambda$StateFragment$c41-_H-DQcT0mFaQTnYWJ-cLprM.onItemClick(Unknown Source:8)
at android.widget.AdapterView.performItemClick(AdapterView.java:362)
at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
at android.widget.AbsListView$7.run(AbsListView.java:6612)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7078)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
```

**Comment by frimtec** [comment]
Cannot reproduce.
