### ISSUE TITLE
ActivityNotFoundException on samsung nexus (with custom ROM for Android 10?)

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#406]
Android version: 29
Device: samsung Nexus
App version: 1130273
Thread name: main

Exception stack trace:
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.android.calendar/time/1677971300689 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2051)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1709)
at android.app.Activity.startActivityForResult(Activity.java:5192)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
at android.app.Activity.startActivityForResult(Activity.java:5150)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
at android.app.Activity.startActivity(Activity.java:5521)
at android.app.Activity.startActivity(Activity.java:5489)
at com.github.frimtec.android.pikettassist.ui.overview.OnCallState.onClickAction(OnCallState.java:71)
at com.github.frimtec.android.pikettassist.ui.overview.StateFragment.lambda$configureListView$2$com-github-frimtec-android-pikettassist-ui-overview-StateFragment(StateFragment.java:158)
at com.github.frimtec.android.pikettassist.ui.overview.StateFragment$$ExternalSyntheticLambda9.onItemClick(Unknown Source:8)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
at android.widget.AbsListView$3.run(AbsListView.java:4116)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by frimtec** [comment]
It seems that no default calender app is available on that device.

We can try to catch the exception to prevent an app crash. 
But anyway without an calender app the use of PAssist is very limited.

**Comment by frimtec** [comment]
Will be fixen in next release.
