### ISSUE TITLE
API-25: WakeLock under-locked exception

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#49]
Android version: 25
Device: HMD Global Nokia 2
App version: 1217
Thread name: main

Exception stack trace:
java.lang.RuntimeException: Unable to destroy activity {com.github.frimtec.android.pikettassist/com.github.frimtec.android.pikettassist.activity.LowSignalAlarmActivity}: java.lang.RuntimeException: WakeLock under-locked LowSignalAlarmActivity:alarm
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4203)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
at android.app.ActivityThread.-wrap6(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.RuntimeException: WakeLock under-locked LowSignalAlarmActivity:alarm
at android.os.PowerManager$WakeLock.release(PowerManager.java:1411)
at android.os.PowerManager$WakeLock.release(PowerManager.java:1377)
at com.github.frimtec.android.pikettassist.activity.AbstractAlarmActivity.onDestroy(AbstractAlarmActivity.java:209)
at android.app.Activity.performDestroy(Activity.java:6949)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
... 9 more

**Comment by frimtec** [comment]
Fix has been sent to user.
Waiting for feedback.

**Comment by frimtec** [comment]
I could reproduce the bug on the android emulator.
The fix works.
